let playersIndicesToNames = {
  "0":"Tarik Khan",
  "1":"Abu Sohel",
  "2":"Rashed Sultan",
  "3":"Masu",
  "4":"Khademul Haque",
  "5":"Tanjib Rizwan",
  "6":"Sharif Ahmed",
  "7":"Tanzir Musabbir",
  "8":"Reazul Hoque",
  "9":"Manar Hasan",
  "10":"Arshad Khandaker",
  "11":"Maher Hasan",
  "12":"Munna Ahaduzzaman",
  "13":"Abu Alam",
  "14":"Golam Kibria",
  "15":"Md Zahedul khan",
  "16":"Fayez Shantanu",
  "17":"Md. Rezaul Haque (Reza)",
  "18":"Mohammad Khan",
  "19":"Sabbir Ahmed",
  "20":"Asab Uddin",
  "21":"Ahmed Pantho",
  "22":"Omar Faruque",
  "23":"Tareq zaman",
  "24":"Ibrahim Ahmed",
  "25":"Golam Morshed Chowdhury",
  "26":"Enam Haq",
  "27":"Mostaqur Sarker",
  "28":"Samin Hossain",
  "29":"Rajib Khan",
  "30":"Enam Haque",
  "31":"Md Moinul Islam",
  "32":"ZahiruI Islam Shaheen",
  "33":"Zayed Islam",
  "34":"Nafis Khan",
  "35":"Zarif Aziz",
  "36":"Wasim Quddus",
  "37":"Shafin",
  "38":"Shamel",
  "39":"Abdullah Fahim",
  "40":"Obaid Rahman",
  "41":"Shwqat",
  "42":"Ruhul Amin Chowdhury",
  "43":"Faisal Rashid",
  "44":"Md Mahmudur Chowdhury",
  "45":"Arshad Hussain Mamun",
  "46":"Rakib Hasan Ayon",
  "47":"Rezwan Rahman",
  "48":"Shahid Zaman",
  "49":"Md Mahabub Hossain",
  "50":"A H M Zuberi Ashraf",
  "51":"Munir Faisal Chowdhury",
  "52":"Samin Ahmed",
  "53":"Mohammad Karim",
  "54":"MD Zulficar Ali",
  "55":"Shams Deen Arif",
  "56":"Aktaruzzaman Aman",
  "57":"MOHAMMAD SIRAJ",
  "58":"Hasan Taufique",
  "59":"Mahmood Hossain",
  "60":"Jahirul Bhuiyan",
  "61":"Raihan Kabir",
  "62":"Mushfiqur Rahman Neon",
  "63":"Sabbir Chowdhury",
  "64":"Hasan Uz Zaman (Mukul)",
  "65":"Afsar Zaman",
  "66":"Mukim Khan",
  "67":"Md Shafiul Azam",
  "68":"Kamrul Russel",
  "69":"Zaayan Islam",
  "70":"MD M KHAN LIMON",
  "71":"Jashim Chowdhury",
  "72":"Ali Erteza Khan",
  "73":"Jamshed Jalal",
  "74":"Oli Bhuiyan",
  "75":"Sharif Ahsan",
  "76":"SoheL Rahaman",
  "77":"Shadman Chowdhury",
  "78":"Sayeed Ahmed Badrudduza",
  "79":"Shanewaz Ahmed",
  "80":"Mehedi Hasan",
  "81":"Arbab Ahmed",
  "82":"Jalal",
  "83":"Ahnaf Ahsan",
  "84":"Anol Saha",
  "85":"Mehedi Khan",
  "86":"Saymon",
  "87":"Faisal Mahmood",
  "88":"Saiful Islam (Niton)",
  "89":"Ehtesham Hoq",
  "90":"Syed Zahed Aziz",
  "91":"Iqbal Mahmud",
  "92":"Ezaz (Rana)",
  "93":"M.M. Hasnat",
  "94":"Md Noor E Alam",
  "95":"Hasan Chowdhury",
  "96":"Zahid Hasan",
  "97":"Kollol Arefin",
  "98":"Bahar",
  "99":"Sazal Islam",
  "100":"Mohammad Rumi",
  "101":"Ahsan Islam",
  "102":"Sheik Mohammad Nomaan",
  "103":"Istiaque Hasan",
  "104":"Zakaria Khwaja",
  "105":"Iqbal hussain",
  "106":"Samiul Islam",
  }

export default playersIndicesToNames;